// src/components/mockProperties.js

const properties = [
  {
    id: "HOU123",
    name: "Bayou Heights Residences",
    location: "Houston, TX",
    image: "property1.jpg",
    yield: "8.25%",
    status: "Available",
    cost: "$175,000",
    funding_phase: "Phase 2 (Est. Completion: Aug 2025)",
  },
  {
    id: "DAL456",
    name: "Maple Drive Duplex",
    location: "Dallas, TX",
    image: "property2.jpg",
    yield: "7.10%",
    status: "Limited Availability",
    cost: "$240,000",
    funding_phase: "Phase 1 (Est. Completion: Oct 2025)",
  },
  {
    id: "ATX789",
    name: "Barton Hills Flats",
    location: "Austin, TX",
    image: "property3.jpg",
    yield: "6.80%",
    status: "Fully Funded",
    cost: "$305,000",
    funding_phase: "Phase 3 (Est. Completion: Dec 2025)",
  },
  {
    id: "SA910",
    name: "Riverwalk Lofts",
    location: "San Antonio, TX",
    image: "property4.jpg",
    yield: "9.00%",
    status: "Available",
    cost: "$190,000",
    funding_phase: "Pre-Funding (Q4 2025)",
  },
  {
    id: "HOU321",
    name: "Galleria Studios",
    location: "Houston, TX",
    image: "property5.jpg",
    yield: "7.85%",
    status: "Available",
    cost: "$210,000",
    funding_phase: "Phase 1 (Est. Completion: Sep 2025)",
  },
  {
    id: "DAL789",
    name: "Elm Townhomes",
    location: "Dallas, TX",
    image: "property6.jpg",
    yield: "7.60%",
    status: "Limited Availability",
    cost: "$265,000",
    funding_phase: "Phase 2 (Est. Completion: Nov 2025)",
  },
  {
    id: "ATX456",
    name: "Zilker Park Villas",
    location: "Austin, TX",
    image: "property7.jpg",
    yield: "8.45%",
    status: "Fully Funded",
    cost: "$325,000",
    funding_phase: "Phase 3 (Est. Completion: Jan 2026)",
  },
  {
    id: "HOU999",
    name: "Midtown Flats",
    location: "Houston, TX",
    image: "property8.jpg",
    yield: "6.95%",
    status: "Available",
    cost: "$185,000",
    funding_phase: "Phase 1 (Est. Completion: Jul 2025)",
  },
  {
    id: "SA222",
    name: "Alamo Heights Estate",
    location: "San Antonio, TX",
    image: "property9.jpg",
    yield: "7.95%",
    status: "Limited Availability",
    cost: "$230,000",
    funding_phase: "Phase 2 (Est. Completion: Oct 2025)",
  },
  {
    id: "ATX333",
    name: "Lake Austin Rowhomes",
    location: "Austin, TX",
    image: "property10.jpg",
    yield: "8.10%",
    status: "Available",
    cost: "$275,000",
    funding_phase: "Pre-Funding (Q1 2026)",
  },
];

export default properties;
